"""empty message

Revision ID: 00c5363acd7d
Revises: 0c8299634e99
Create Date: 2021-09-19 14:23:56.292551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00c5363acd7d'
down_revision = '0c8299634e99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'category', ['name'])
    op.alter_column('order', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('product', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('order', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'category', type_='unique')
    # ### end Alembic commands ###
